# Generated by Django 2.2.7 on 2020-06-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200605_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='staff'),
        ),
    ]
