# Generated by Django 2.2.7 on 2020-06-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200605_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('option', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Option')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='superuser'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
