# Generated by Django 2.2.7 on 2020-06-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200605_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Poll'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(default=1, max_length=20, null=True),
        ),
    ]
